### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.3
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: RAG_ProGuide
template: qwen
cutoff_len: 10000
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: saves/qwen2.5-7b-instruct/full/dpo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.2
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
                                                                   
